### ISSUE TITLE
Error: assertion failure with message: unable to find key

### ISSUE THREAD

**Issue by zhangze2** [Press-One/prs-atm#10]
**Describe the bug**
Error: PRS API > Error: assertion failure with message: unable to find key

**To Reproduce**
1. prs-atm reward --account=guard --keystore=keystore.json
2. See error

**Expected behavior**
reward Success

**Screenshots**
NULL.

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.5 (19F101)]
 - prs-atm version [v2.0.31]
- Node version : v13.11.0

**Additional context**
NULL.

**Comment by Leask** [comment]
Only the BP accounts can claim rewards.
