### ISSUE TITLE
升级2.0 链之后，运行prs-atm balance account  显示无该账号

### ISSUE THREAD

**Issue by huangchen2005** [Press-One/prs-atm#12]
运行docker run -i  -v /data:/data  pressone/prs-atm prs-atm balance --account=pressone
返回Error: Account not found: pressone

这个账号之前是存在的，且里边有prs，升级之后就找不到了

**Comment by Leask** [comment]
這個帳戶有問題，應該其他地方已經溝通過了，這邊先關閉了。
