### ISSUE TITLE
提现申请

### ISSUE THREAD

**Issue by firefly1126** [Press-One/prs-atm#13]
foxone团队的几个账号申请提现，账号如下：

* edoprs
* haoprs
* longprs
* prsheng
* qingprs
* ukiyo
* xiaoming

麻烦尽快通过一下，我们急需等待把提现的PRS重新质押到（foxone, foxprs, freefox）三个节点重新投票。

**Comment by virushuo** [comment]
只收到了两个，已经完成了。

**Comment by firefly1126** [comment]
其他的提现申请，我执行`withdraw`的时候都有正确的response回来，你们没有收到申请吗？

**Comment by firefly1126** [comment]
其他的账户我check了balance, 都已经是0 PRS了，应该是申请成功了

**Comment by virushuo** [comment]
好的。那么就close了。
