### ISSUE TITLE
deposit后账户余额没有更新

### ISSUE THREAD

**Issue by firefly1126** [Press-One/prs-atm#15]
**Describe the bug**
foxone节点 执行`deposit`后，余额没有更新，且用`balance`命令，返回 `Error: Account not found: foxone`，用`account`可以正常返回。

支付链接:
```
https://mixin.one/pay?recipient=beb05804-f083-498e-ac0f-af6d7fbcd694&asset=3edb734c-6d6f-32ff-ab03-4eb43640c758&amount=5335735.0000&trace=c37580a0-17fb-11eb-85e9-a3dfad9a50fc&memo=Deposit%20on%20PRESS.one
```

**Expected behavior**
-期望执行`deposit`后，余额更新
-`balance`命令有效

**Desktop (please complete the following information):**
 - OS: macOS catalina
 - Version：10.15.6

**Comment by Leask** [comment]
後來收到錢了麼？

**Comment by Leask** [comment]
之前你充值那天服務器有一點不穩定，現在已經已經完全恢復了，請問後來到帳了麼？如果還沒到，我明天給你查查。

**Comment by firefly1126** [comment]
问题已解决，谢谢。
