### ISSUE TITLE
galaxy节点提现未到账，请审核

### ISSUE THREAD

**Issue by zhangze2** [Press-One/prs-atm#17]
╔════════════════════════════════╤══════════════════════════════════════════════════════════════════════════════════╗
║ CHAINACCOUNT                   │ galaxy                                                                           ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ MIXINACCOUNT                   │ f11bf8b9-eb48-4468-a520-dbd7b1ed5a15                                             ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ EMAIL                          │ zhangze.zz@qq.com                                                                ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ CURRENCY                       │ PRS                                                                              ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ AMOUNT                         │ 300000.0000                                                                      ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ TRACE                          │ 8df720ad-350e-55df-a8da-b3041e6490ba                                             ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ REQUESTID                      │ 1615464423014                                                                    ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ MEMO                           │ Withdraw from PRESS.one                                                          ║
╟────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────╢
║ TRANSACTION_ID                 │ a3fad91f80ac054ffa41a9aa812ea14bb761ee007f2d9fb39df556b1725a78a9                 ║
╚════════════════════════════════╧══════════════════════════════════════════════════════════════════════════════════╝

**Comment by zhangze2** [comment]
没有到账

**Comment by Leask** [comment]
剛查過，已經倒帳啦。
