### ISSUE TITLE
producer yihang is not registered

### ISSUE THREAD

**Issue by zhangze2** [Press-One/prs-atm#19]
**Describe the bug**
Error: PRS API > Error: assertion failure with message: producer yihang is not registered'

**To Reproduce**

在 prs-atm 图形界面搜索不到账户 yihang 。给这个账户用命令行投票提示如下 ：
Error: PRS API > Error: assertion failure with message: producer yihang is not registered'

![image](https://user-images.githubusercontent.com/6898639/115325008-77755080-a1bd-11eb-80d8-9c69c947d92d.png)

**Comment by raimonfuns** [comment]
你好。
看起来你这个账号还没有注册成为节点。所以无法在节点列表中搜索到。
你可以使用 BpReg 命令，注册成为节点，然后就可以搜索到，也可以被投票

如何注册成为节点？方法如下：

=====================================================================

* `BpReg` > Register as a Producer:

    --account  PRESS.one account                 [STRING  / REQUIRED]
    --url      URL where info about producer     [STRING  / OPTIONAL]
    --location Relative location for scheduling  [INTEGER / OPTIONAL]
    --keystore Path to the keystore JSON file    [STRING  / OPTIONAL]
    --password Use to decrypt the keystore       [STRING  / OPTIONAL]
    --pubkey   PRESS.one public key              [STRING  / OPTIONAL]
    --pvtkey   PRESS.one private key             [STRING  / OPTIONAL]
    ┌- NOTICE ------------------------------------------------------┐
    | `keystore` (recommend) or `pubkey, pvtkey` must be provided.  |
    └---------------------------------------------------------------┘

    > Example:
    $ prs-atm BpReg \
              --account=ABCDE \
              --keystore=keystore.json

=====================================================================

**Comment by zhangze2** [comment]
投其它节点后注册成功，已解决
