### ISSUE TITLE
prs-atm withdraw no effect

### ISSUE THREAD

**Issue by firefly1126** [Press-One/prs-atm#2]
**Describe the bug**
prs-atm withdraw response correct, but no effect. no statement and no real transaction.

**To Reproduce**
1. Do withdraw command:

```
prs-atm withdraw --account foxprs --mx-id=c69756ac-70c1-3b1b-8ee9-c9607acfa75c --amount=1544 --keystore=foxprs-keystore.json --password="xxxxx" --email=xiaoming1109@gmail.com --json --debug --spdtest 
```
2. And response:

```
{
  "chainAccount": "foxprs",
  "mixinId": "c69756ac-70c1-3b1b-8ee9-c9607acfa75c",
  "mixinNumber": "",
  "email": "xiaoming1109@gmail.com",
  "currency": "PRS",
  "amount": "1544.0000",
  "trace": "1b7e3ab0-ca60-11ea-8e86-c3ace25b1f63",
  "requestId": 1595232471515,
  "memo": "Withdraw from PRESS.one"
}
```

3. But no transaction record in statement, and no real transaction. 

**Expected behavior**
1-Correct response with correct transaction

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Additional context**

**Comment by Leask** [comment]
任何時候，你可以通過 prs-atm statement --account=foxprs --detail 查詢到轉帳失敗的原因。留意後面的 --detail 參數，帶上這個參數可以讓返回結果中帶上失敗的紀錄，以及失敗的詳細原因。

**Comment by Leask** [comment]
團隊經過討論，決定把通過mixin id/uuid轉帳的時候，跳過必須是充值過的帳戶，這個檢查，但是具體的風險需要自己承擔，具體我們最近會升級代碼。升級完會在文檔中提現，這個issue先關閉，如果到時候再重現這個問題，請重新開新的issue。感謝。
