### ISSUE TITLE
两笔 500pr 充值只到账一笔问题

### ISSUE THREAD

**Issue by zhangze2** [Press-One/prs-atm#20]
**Describe the bug**
往 prs-atm 的两笔 500pr 充值只到账一笔

**充值记录**
PRESS.one DEPOSIT Notification

DEPOSIT SUCCESS

Request ID: 4855489632
Account: yihang
Mixin Trace ID: 49064bc9-0919-59a3-9048-7ab2dfa420f7
Amount: 100.0000 PRS
Memo: 转入 PRS ATM
Request Time: Sat Apr 17 2021 13:11:07 GMT+0000 (Coordinated Universal Time)
Processed Time: Sat Apr 17 2021 13:11:39 GMT+0000 (Coordinated Universal Time)

DEPOSIT PAYMENT REQUEST
Memo: 转入 PRS ATM

Amount: 500.0000 SRP
Payment URL: https://mixin.one/pay?recipient=beb05804-f083-498e-ac0f-af6d7fbcd694&asset=3edb734c-6d6f-32ff-ab03-4eb43640c758&amount=500.0000&trace=1ce6dc11-4fd9-5e28-9fd6-dee8835d0905&memo=%E8%BD%AC%E5%85%A5%20PRS%20ATM

DEPOSIT PAYMENT REQUEST
Memo: 转入 PRS ATM

Amount: 500.0000 SRP
Payment URL: https://mixin.one/pay?recipient=beb05804-f083-498e-ac0f-af6d7fbcd694&asset=3edb734c-6d6f-32ff-ab03-4eb43640c758&amount=500.0000&trace=6cfee6f0-ed6c-5bbf-855c-7777df6f68db&memo=%E8%BD%AC%E5%85%A5%20PRS%20ATM

PRESS.one DEPOSIT Notification

DEPOSIT SUCCESS

Request ID: 1623585073104
Account: yihang
Mixin Trace ID: 6cfee6f0-ed6c-5bbf-855c-7777df6f68db
Amount: 500.0000 PRS
Memo: 转入 PRS ATM
Request Time: Wed Apr 21 2021 13:05:02 GMT+0000 (Coordinated Universal Time)
Processed Time: Wed Apr 21 2021 13:06:43 GMT+0000 (Coordinated Universal Time)

**Comment by Leask** [comment]
已經修復。
