### ISSUE TITLE
超级节点排名和收益不相符

### ISSUE THREAD

**Issue by cohen-zhang** [Press-One/prs-atm#21]
**Describe the bug**
超级节点 Galaxy 排名和收益不相符

**To Reproduce**
比较了 galaxy 和 guard 节点的每日收益， 排名靠前的 galaxy 收益比 guard 低

**Comment by cmcater** [comment]
能否提供3天的具体收益比较

**Comment by zhangze2** [comment]
![image](https://user-images.githubusercontent.com/6898639/116195614-086f9d00-a765-11eb-81e0-68aa1d02d395.png)

**Comment by liujuanjuan1984** [comment]
![image](https://user-images.githubusercontent.com/31027645/116434791-4cee5c00-a87d-11eb-92ee-8239c783e9e4.png)

根据 galaxy 和 guard 的statement 收益流水做的对比图，galaxy 并非总是比 guard 少。

收益跟申领那一刻的一些动态的参数有关。并不是bug。如果不放心，可以多观察一段时间。

**Comment by liujuanjuan1984** [comment]
如果某个时段申领收益的bp较为扎堆，后领取收益的bp收益可能会略低一些。

应对策略，可以不用管。长期来看，多干活就会收益更高。

如果在意，那么可以选择在申领收益的bp较少的时段去申领。（重新设一下自动申领收益的时间）

**Comment by zhangze2** [comment]
好的，理解了，多谢
