### ISSUE TITLE
About "ballot"

### ISSUE THREAD

**Issue by taoran777** [Press-One/prs-atm#3]
**Describe the bug** 
When I execute the command "$ prs-atm ballot", it returns "TypeError: Only absolute URLs are supported"。
How can I get the right infomation. Thanks.

**To Reproduce** 

**Expected behavior** 

**Screenshots**
 xx@xxxx:~$ prs-atm ballot
TypeError: Only absolute URLs are supported
 xx@xxxx:~$ 

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - Version [18.04.1 LTS]

**Smartphone (please complete the following information):** 

**Additional context**

**Comment by Leask** [comment]
Please let me know your prs-atm version.

**Comment by Leask** [comment]
This bug has been fixed at the latest version.

**Comment by taoran777** [comment]
> Please let me know your prs-atm version.

 PACKAGE_VERSION      v2.0.23        
 NODE_VERSION            v11.3.0

**Comment by taoran777** [comment]
After upgrading prs-atm, it is normal. Thank you
