### ISSUE TITLE
About staked

### ISSUE THREAD

**Issue by taoran777** [Press-One/prs-atm#6]
When I executed "delegated --cpu=40 --net=40", I found that the number of "STAKED" was 840000, not 800000. And I can not undelegate this extra part. Why?

**Comment by Leask** [comment]
Please tell us your account name so that we can look into it.

**Comment by taoran777** [comment]
> Please tell us your account name so that we can look into it.

jxnc.ptrsoft

**Comment by cmcater** [comment]
Below is your account status, I can not verify your issue. 

===========================================================
memory:
     quota:     60.55 KiB    used:     4.016 KiB

net bandwidth:
     staked:          4.0000 SRP           (total stake delegated from account to self)
     delegated:       0.0000 SRP           (total staked delegated to account from others)
     used:                 0 bytes
     available:        9.588 MiB
     limit:            9.588 MiB

cpu bandwidth:
     staked:          4.0000 SRP           (total stake delegated from account to self)
     delegated:       0.0000 SRP           (total staked delegated to account from others)
     used:               354 us
     available:        14.54 min
     limit:            14.54 min

SRP balances:
     liquid:           95.0000 SRP
     staked:            8.0000 SRP
     unstaking:         0.0000 SRP
     total:           103.0000 SRP

producers:
     aipress         bigone          bruce
     foxone

===========================================================
If you can, please add more description for this issue. 
For example,  you can paste the full prs-atm command you run when have this issue.

**Comment by Leask** [comment]
@taoran777 If there is no further progress. I will close this issue next week. Thanks.
