### ISSUE TITLE
delegate failed

### ISSUE THREAD

**Issue by firefly1126** [Press-One/prs-atm#7]
**Describe the bug**
执行 `prs-atm delegate --account=feiprs --receiver=feiprs --keystore=config/feiprs-keystore.json --password="xxxx" --cpu=500000 --net=500000 --json --debug`

response:

```
errorCode: 5000, errorMsg unexpected end of JSON input
```

**To Reproduce**
1. qingprs delegate了100万到feiprs, 然后参与了投票；
2. 后面qingprs undelegate给feiprs的100万；
3. 重新充值给feiprs100万，然后执行delegate 给feiprs自己
4. 发现delegate失败，其他节点没有这样的问题

怀疑导致该问题的原因是：qingprs 执行delegate时 receiver指向了feiprs, 然后又undelegate了，导致feiprs无法自己delegate给自己。

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Leask** [comment]
Error `unexpected end of JSON input` means your keystore file is invalid. Please check your keystore file.
