### ISSUE TITLE
Error `unexpected end of JSON input` means your keystore file is invalid. Please check your keystore file.

### ISSUE THREAD

**Issue by firefly1126** [Press-One/prs-atm#8]
Error `unexpected end of JSON input` means your keystore file is invalid. Please check your keystore file.

_Originally posted by @Leask in https://github.com/Press-One/prs-atm/issues/7#issuecomment-664636901_

Keystore file is correct, it can be unlocked  with command `unlock`.

**Comment by firefly1126** [comment]
And `withdraw` responses the same error `unexpected end of JSON input` also.

**Comment by firefly1126** [comment]
Client: {
  "account": "feiprs",
  "signatureProvider": {
    "keys": {},
    "availableKeys": [
      "PUB_K1_8g8F5chfrWjcf4wK9Rn5puktUTBm3p7PM4gxm2U3pw3TdyP9jE"
    ]
  },
  "api": {
    "contracts": {},
    "cachedAbis": {},
    "rpc": {
      "endpoint": "http://5.135.106.40:8888"
    },
    "authorityProvider": {
      "endpoint": "http://5.135.106.40:8888"
    },
    "abiProvider": {
      "endpoint": "http://5.135.106.40:8888"
    },
    "signatureProvider": {
      "keys": {},
      "availableKeys": [
        "PUB_K1_8g8F5chfrWjcf4wK9Rn5puktUTBm3p7PM4gxm2U3pw3TdyP9jE"
      ]
    },
    "chainId": "3e862a165d4576aef33af5fec649073dc51362a97d8df43fc6a4331fc1c6764f",
    "textEncoder": {},
    "textDecoder": {},
    "abiTypes": {},
    "transactionTypes": {}
  }
}

Actor: feiprs (5HwdFLMwRaW73Wgagd9LKVSWxwZ7N3kR4YsL23fX5psaLkHpbQV)

Action: prs.tproxy -> reqwithdraw

Payload: {
  "actions": [
    {
      "account": "prs.tproxy",
      "name": "reqwithdraw",
      "data": {
        "user": "feiprs",
        "withdraw_id": 1595909258588,
        "mixin_trace_id": "e00619c0-d087-11ea-a292-4f45d6fecea2",
        "mixin_account_id": "{\"mixinId\":\"35837303\",\"email\":\"xiaoming1109@gmail.com\"}",
        "amount": "200000.0000 SRP",
        "memo": "Withdraw from PRESS.one"
      },
      "authorization": [
        {
          "actor": "feiprs",
          "permission": "active"
        }
      ]
    }
  ]
}

RPC Error: {
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3090003,
    "name": "unsatisfied_authorization",
    "what": "Provided keys, permissions, and delays do not satisfy declared authorizations",
    "details": [
      {
        "message": "transaction declares authority '${auth}', but does not have signatures for it under a provided delay of 0 ms, provided permissions ${provided_permissions}, provided keys ${provided_keys}, and a delay max limit of 3888000000 ms",
        "file": "authorization_manager.cpp",
        "line_number": 524,
        "method": "check_authorization"
      }
    ]
  }
}

================================================================================================================================================================================================================================================================================================================================
Error: PRS API > Error: transaction declares authority '${auth}', but does not have signatures for it under a provided delay of 0 ms, provided permissions ${provided_permissions}, provided keys ${provided_keys}, and a delay max limit of 3888000000 ms
    at Object.throwError (/usr/local/lib/node_modules/prs-atm/node_modules/utilitas/lib/utilitas.js:198:25)
    at throwRpcError (/usr/local/lib/node_modules/prs-atm/node_modules/sushitrain/lib/sushitrain.js:80:18)
    at Object.transact (/usr/local/lib/node_modules/prs-atm/node_modules/sushitrain/lib/sushitrain.js:189:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by firefly1126** [comment]
But `deposit` can response correctly.
CMD:
 `prs-atm deposit --account foxone --keystore config/foxone-keystore.json --password "xxxx" --amount 100 --email xiaoming1109@gmail.com --rpcapi http://54.178.3.36:8888 --json`

response:

```
{
  "chainAccount": "foxone",
  "mixinId": "",
  "mixinNumber": "",
  "email": "xiaoming1109@gmail.com",
  "currency": "PRS",
  "amount": "100.0000",
  "trace": "75074890-d089-11ea-a213-417b8afb3df5",
  "requestId": 1595909938073,
  "memo": "Deposit on PRESS.one",
  "paymentUrl": "https://mixin.one/pay?recipient=beb05804-f083-498e-ac0f-af6d7fbcd694&asset=3edb734c-6d6f-32ff-ab03-4eb43640c758&amount=100.0000&trace=75074890-d089-11ea-a213-417b8afb3df5&memo=Deposit%20on%20PRESS.one",
  "paymentTimeout": "2020-08-04T04:19:00.684Z"
}
{"amount":"100.0000","chainAccount":"foxone","currency":"PRS","email":"xiaoming1109@gmail.com","memo":"Deposit on PRESS.one","mixinId":"","mixinNumber":"","paymentTimeout":"2020-08-04T04:19:00.684Z","paymentUrl":"https://mixin.one/pay?recipient=beb05804-f083-498e-ac0f-af6d7fbcd694\u0026asset=3edb734c-6d6f-32ff-ab03-4eb43640c758\u0026amount=100.0000\u0026trace=75074890-d089-11ea-a213-417b8afb3df5\u0026memo=Deposit%20on%20PRESS.one","requestId":1595909938073,"trace":"75074890-d089-11ea-a213-417b8afb3df5"}
```

**Comment by Leask** [comment]
@firefly1126 one of your comment leaks your private key! I deleted it for you. For your safety please transfer your PRS to a new account ASAP. I will disable private-key debug output in the next `prs-arm` release.

**Comment by Leask** [comment]
> And `withdraw` responses the same error `unexpected end of JSON input` also.

Another point, please run `auth` command before the fist withdrawal. That is not the same error as `unexpected end of JSON input`.

`unexpected end of JSON input` ONLY SHOWS when you use an invalid key file.

**Comment by Leask** [comment]
I will close this issue. If you repeat your problem, you can open another one.
