### ISSUE TITLE
prs-atm withdraw: User has submited request, wait till the current request finished

### ISSUE THREAD

**Issue by dbarobin** [Press-One/prs-atm#9]
**Describe the bug**
When I withdraw use prs-atm, the error shows:

> Error: PRS API > Error: assertion failure with message: User has submited request, wait till the current request finished

**To Reproduce**
1. prs-atm withdraw --amount=100000.0000 --account=xxx --mx-num=xxx --email=xxx@xxx.com --json --keystore=keystore.json

**Expected behavior**
The PRS withdrawn is shown in the Mixin wallet.

**Screenshots**
NULL.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0 Beta (20A5364e)
 - prs-atm version: v2.0.31
- node version: v12.18.2

**Additional context**
NULL.

**Comment by Leask** [comment]
You can use the `cancel ` command to cancel an on-going transaction request.
